# Generated by Django 5.1.1 on 2024-09-20 14:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('parcel', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AutorisationUrbanismeWorkflow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.CharField(choices=[('step_one', 'Step One'), ('step_two', 'Step Two'), ('step_three', 'Step Three'), ('completed', 'Completed')], default='step_one', max_length=20)),
                ('tnb_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Montant TNB')),
                ('tnb_payment_date', models.DateField(blank=True, null=True, verbose_name='Date de Paiement TNB')),
                ('autorisation_number', models.CharField(blank=True, max_length=250, null=True, verbose_name='Numéro de Décision Autorisation')),
                ('autorisation_date', models.DateField(blank=True, null=True, verbose_name='Date de Décision Autorisation')),
                ('attestation_number', models.CharField(blank=True, max_length=250, null=True, verbose_name='Numéro de Décision Attestation')),
                ('attestation_date', models.DateField(blank=True, null=True, verbose_name='Date de Décision Attestation')),
                ('parcel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='upawork', to='parcel.parcel')),
            ],
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document', models.FileField(upload_to='urbanisme/documents/')),
                ('name', models.CharField(max_length=255)),
                ('document_type', models.CharField(choices=[('tnb_document', 'TNB'), ('plan_authorized_document', 'Plan autorisé'), ('attestation_document', 'Attestation de conformité')], max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('workflow', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='upaworkflow.autorisationurbanismeworkflow')),
            ],
        ),
    ]
