# Generated by Django 5.0.7 on 2024-10-17 17:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('upaworkflow', '0002_autorisationurbanismeworkflow_created_at'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='autorisationurbanismeworkflow',
            options={'verbose_name': 'Autorisation Urbanisme Workflow', 'verbose_name_plural': 'Autorisation Urbanisme Workflows'},
        ),
        migrations.AlterModelOptions(
            name='document',
            options={'verbose_name': 'Urbanisme Document', 'verbose_name_plural': 'Urbanisme Documents'},
        ),
        migrations.AlterField(
            model_name='document',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Created At'),
        ),
        migrations.AlterField(
            model_name='document',
            name='document',
            field=models.FileField(upload_to='urbanisme/documents/', verbose_name='Document'),
        ),
        migrations.AlterField(
            model_name='document',
            name='document_type',
            field=models.CharField(choices=[('tnb_document', 'TNB'), ('plan_authorized_document', 'Plan autorisé'), ('attestation_document', 'Attestation de conformité')], max_length=255, verbose_name='Document Type'),
        ),
        migrations.AlterField(
            model_name='document',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='document',
            name='workflow',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='upaworkflow.autorisationurbanismeworkflow', verbose_name='Workflow'),
        ),
    ]
