# Generated by Django 5.1.1 on 2024-09-20 14:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('parcel', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CombustibleWorkflow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Company Name')),
                ('station_type', models.CharField(blank=True, max_length=255, null=True, verbose_name='Station Type')),
                ('urban_rural', models.CharField(blank=True, choices=[('urban', 'Urban'), ('rural', 'Rural')], max_length=10, null=True, verbose_name='Urban/Rural')),
                ('decision_number', models.CharField(blank=True, max_length=255, null=True, verbose_name='Decision Number')),
                ('decision_date', models.DateField(blank=True, null=True, verbose_name='Decision Date')),
                ('manager', models.CharField(blank=True, max_length=255, null=True, verbose_name='Manager')),
                ('status', models.CharField(blank=True, max_length=255, null=True, verbose_name='Status')),
                ('management_type', models.CharField(blank=True, max_length=255, null=True, verbose_name='Management Type')),
                ('creation_number', models.CharField(blank=True, max_length=255, null=True, verbose_name='Creation Number')),
                ('creation_date', models.DateField(blank=True, null=True, verbose_name='Creation Date')),
                ('service_number', models.CharField(blank=True, max_length=255, null=True, verbose_name='Service Number')),
                ('service_date', models.DateField(blank=True, null=True, verbose_name='Service Date')),
                ('state', models.CharField(choices=[('step_one', 'Step 1'), ('step_two', 'Step 2'), ('completed', 'Completed')], default='step_one', max_length=20, verbose_name='State')),
                ('parcel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='combustiblework', to='parcel.parcel', verbose_name='Parcel')),
            ],
        ),
        migrations.CreateModel(
            name='CombustibleDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document', models.FileField(upload_to='combustible/documents/', verbose_name='Document')),
                ('name', models.CharField(max_length=255, verbose_name='Name')),
                ('document_type', models.CharField(choices=[('combustible_creation', 'Combustible Creation'), ('mise_en_service', 'Mise En Service')], max_length=20, verbose_name='Document Type')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('workflow', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='combustibleworkflow.combustibleworkflow', verbose_name='Workflow')),
            ],
        ),
    ]
