# Generated by Django 5.0.7 on 2024-10-17 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('combustibleworkflow', '0002_combustibleworkflow_created_at'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='combustibledocument',
            options={'verbose_name': 'Combustible Document', 'verbose_name_plural': 'Combustible Documents'},
        ),
        migrations.AlterModelOptions(
            name='combustibleworkflow',
            options={'verbose_name': 'Combustible Workflow', 'verbose_name_plural': 'Combustible Workflows'},
        ),
        migrations.AlterField(
            model_name='combustibleworkflow',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Created At'),
        ),
    ]
