# Generated by Django 5.1.1 on 2024-09-20 14:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('parcel', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OccupationWorkflow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nature_occupation', models.CharField(blank=True, max_length=255, null=True, verbose_name='Nature of Occupation')),
                ('decision_number', models.CharField(blank=True, max_length=255, null=True, verbose_name='Decision Number')),
                ('decision_date', models.DateField(blank=True, null=True, verbose_name='Decision Date')),
                ('duration', models.PositiveIntegerField(blank=True, null=True, verbose_name='Duration (years)')),
                ('route_reference', models.CharField(blank=True, max_length=255, null=True, verbose_name='Route Reference')),
                ('state', models.CharField(choices=[('step_one', 'Step 1'), ('step_two', 'Step 2'), ('completed', 'Completed')], default='step_one', max_length=20, verbose_name='State')),
                ('parcel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='occupationwork', to='parcel.parcel', verbose_name='Parcel')),
            ],
        ),
        migrations.CreateModel(
            name='YearlyOccupationData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('area_occupation', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Occupation Area (sqm)')),
                ('royalty_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Royalty Amount')),
                ('workflow', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='yearly_data', to='occupationtempworkflow.occupationworkflow', verbose_name='Workflow')),
            ],
        ),
        migrations.CreateModel(
            name='OccupationDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document', models.FileField(upload_to='occupation/documents/', verbose_name='Document')),
                ('name', models.CharField(max_length=255, verbose_name='Name')),
                ('document_type', models.CharField(choices=[('temporary_occupation_document', 'Step 1'), ('payment_receipt_document', 'Step 2')], max_length=30, verbose_name='Document Type')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('workflow', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='occupationtempworkflow.occupationworkflow', verbose_name='Workflow')),
                ('yearly_data', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='occupationtempworkflow.yearlyoccupationdata', verbose_name='Yearly Data')),
            ],
        ),
    ]
