# Generated by Django 5.1.1 on 2024-09-20 14:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('parcel', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FoncierWorkflow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.CharField(choices=[('step_one', 'Step One'), ('step_two', 'Step Two'), ('step_three', 'Step Three'), ('step_four', 'Step Four'), ('step_five', 'Step Five'), ('step_six', 'Step Six'), ('step_seven', 'Step Seven'), ('completed', 'Completed')], default='step_one', max_length=20, verbose_name='Workflow State')),
                ('nature_du_projet', models.TextField(blank=True, null=True, verbose_name='Nature du Projet')),
                ('prix_m2', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Prix/m²')),
                ('prix_total', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Prix Total')),
                ('proprietaire', models.CharField(blank=True, max_length=255, null=True, verbose_name='Propriétaire')),
                ('date_de_paiement', models.DateField(blank=True, null=True, verbose_name='Date de Paiement')),
                ('paiement_montant', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Montant du Paiement')),
                ('numero_de_titre', models.CharField(blank=True, max_length=255, null=True, verbose_name='Numéro de Titre')),
                ('parcel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='foncier', to='parcel.parcel', verbose_name='Parcel')),
            ],
        ),
        migrations.CreateModel(
            name='FoncierDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document', models.FileField(upload_to='foncier/documents/')),
                ('name', models.CharField(max_length=255)),
                ('document_type', models.CharField(choices=[('cahier_de_charges', 'Cahier de charges'), ('payment_document', 'Paiement'), ('attestation_of_split', 'Attestation de morceler'), ('technical_dossier', 'Dossier technique'), ('notary', 'Notaire'), ('property_certificate', 'Certificat de propriété'), ('cadastral_plan', 'Plan cadastral'), ('containment_calculation', 'Calcul de contenance'), ('quitus', 'Quitus')], max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('workflow', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='foncierworkflow.foncierworkflow')),
            ],
        ),
    ]
