# Generated by Django 5.0.7 on 2024-10-17 17:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foncierworkflow', '0003_foncierworkflow_created_at'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='foncierdocument',
            options={'verbose_name': 'Foncier Document', 'verbose_name_plural': 'Foncier Documents'},
        ),
        migrations.AlterModelOptions(
            name='foncierworkflow',
            options={'verbose_name': 'Foncier Workflow', 'verbose_name_plural': 'Foncier Workflows'},
        ),
        migrations.AlterField(
            model_name='foncierdocument',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Created At'),
        ),
        migrations.AlterField(
            model_name='foncierdocument',
            name='document',
            field=models.FileField(upload_to='foncier/documents/', verbose_name='Document'),
        ),
        migrations.AlterField(
            model_name='foncierdocument',
            name='document_type',
            field=models.CharField(choices=[('cahier_de_charges', 'Cahier de charges'), ('payment_document', 'Paiement'), ('attestation_of_split', 'Attestation de morceler'), ('technical_dossier', 'Dossier technique'), ('notary', 'Notaire'), ('property_certificate', 'Certificat de propriété'), ('cadastral_plan', 'Plan cadastral'), ('containment_calculation', 'Calcul de contenance'), ('quitus', 'Quitus')], max_length=255, verbose_name='Document Type'),
        ),
        migrations.AlterField(
            model_name='foncierdocument',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='foncierdocument',
            name='workflow',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='foncierworkflow.foncierworkflow', verbose_name='Workflow'),
        ),
    ]
