# Generated by Django 5.1.1 on 2024-09-20 14:50

import django.contrib.gis.db.models.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Province',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('province', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cities', to='parcel.province')),
            ],
        ),
        migrations.AddField(
            model_name='province',
            name='region',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='provinces', to='parcel.region'),
        ),
        migrations.CreateModel(
            name='Parcel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parcel_type', models.CharField(choices=[('bare land', 'Bare Land'), ('service station', 'Service Station'), ('building', 'Building'), ('warehouse', 'Warehouse'), ('fishing supply point', 'Fishing Supply Point')], max_length=50)),
                ('name', models.CharField(max_length=100)),
                ('situation', models.CharField(max_length=200)),
                ('land_reference', models.CharField(max_length=100)),
                ('area', models.IntegerField()),
                ('coordinates', django.contrib.gis.db.models.fields.PolygonField(srid=4326)),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='parcel.city')),
                ('province', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='parcel.province')),
                ('region', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='parcel.region')),
            ],
        ),
    ]
