# Generated by Django 5.0.7 on 2024-11-07 07:37

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('parcel', '0004_alter_parcel_options_remove_parcel_superficie_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parcel',
            name='coordinates',
            field=django.contrib.gis.db.models.fields.PointField(srid=4326, verbose_name='Coordinates'),
        ),
    ]
